### ISSUE TITLE
As a developer I need to implement a 500 for unrecoverable errors in the system, so that users can be instructed how to proceed

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#10]

**Comment by chathugaj** [comment]
**Acceptance Criteria**

- [x] The system detects internal server errors and triggers an error page for 500 status code.
- [x] A dedicated and visually distinct error page is displayed for 500 errors.
- [x] The error page displays a user-friendly message explaining the error.
- [x] The page provides guidance on how users can proceed.
- [x] The website's branding is maintained on the error page.

**Tasks**

- [x] Handle errors correctly in the system.
- [x] Implement dedicated page for the http 500 errors.
- [x] Provide clear messages and guidance to users.
