### ISSUE TITLE
As a developer I want to redirect unauthorized users to 403 page, so that I can secure my view

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#11]

**Comment by chathugaj** [comment]
**Acceptance Criteria**

- [ ]  The system detects internal server errors and triggers an error page for 403 status code.
- [ ]  A dedicated and visually distinct error page is displayed for 403 errors.
- [ ]  The error page displays a user-friendly message explaining the error.
- [ ]  The page provides guidance on how users can proceed.
- [ ]  The website's branding is maintained on the error page.

**Tasks**

- [ ]  Handle errors correctly in the system.
- [ ]  Implement dedicated page for the http 403 errors.
- [ ]  Provide clear messages and guidance to users.
