### ISSUE TITLE
As the restaurant owner I want to show the menu, so that customer can view it in the website

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#13]

**Comment by chathugaj** [comment]
**Acceptance Criteria**

- [x] The restaurant menu is clearly displayed on the website.
- [x] Menu items are categorized and described in a user-friendly way.

**Tasks**

- [x] Display the menu structure
