### ISSUE TITLE
As the restaurant owner I want my staff to be able to view current reservations of the restaurant, so that we can modify, cancel an existing reservation upon customer request

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#16]

**Comment by chathugaj** [comment]
**Acceptance Criteria**

- [x] Staff members can access a list of all current reservations upon login.
- [x] Clicking on a reservation displays detailed information about the booking.
- [x] Staff can modify certain reservation details.
- [x] Staff can cancel reservations
- [ ] Staff can search and filter reservations
- [x] Customers receive automated notifications about reservation changes

**Tasks**

- [x] Reservation list
- [x] Reservation details
- [x] Modification, cancellation
- [ ] Filter and search
