### ISSUE TITLE
As a customer I want to be able to create an account in the restaurant website, so that I can easily reserve tables next time

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#17]

**Comment by chathugaj** [comment]
**Acceptance Criteria**
- [x] Account registration option is clear and accessible.
- [x] The registration form requests essential information for creating an account.
- [x] The system validates the information during registration.
- [x] After successful validation a customer account is created in the system.
- [x] A welcome email is sent to the customer upon successful account creation.

**Tasks**
- [x] A link or a button to trigger account creation process
- [x] A registration form capturing required information. username, password, etc....
- [x] Customer receives a welcome email
