### ISSUE TITLE
As the restaurant owner I want customers to login, to view their reservations

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#19]

**Comment by chathugaj** [comment]
**Acceptance Criteria**
- [x] Customers can login to the system using their username and password.
- [x] The system displays a list of the customer's upcoming reservations upon successful login.
- [x] The reservation list shows relevant information for each reservation.
- [x] Customers can view detailed information for each reservation.
- [x] The system allows for reservation cancellation.
- [x] Customers can modify visible reservations.

**Tasks**
- [x] The system should allow customers to login using a username or email address and password.
- [x] Upon successful login, the customer should be presented with a list of their upcoming reservations.
- [x] Customers should be able to view the details of each reservation by clicking on it.
- [x] The details page should provide additional information
