### ISSUE TITLE
As a developer I have to create the main layout using HTML, so that the layout can be reused

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#2]

**Comment by chathugaj** [comment]
**Acceptance Criteria**

- [x] The main layout of the website is created using HTML.
- [x] The layout utilizes a clear and reusable structure with dedicated sections for header, navigation, main content, footer.
- [x] Semantic HTML elements are used throughout the layout to define the meaning and purpose of each section.

**Tasks**

- [x] Implement Header
- [x] Implement footer
- [x] Implement Navigation
