### ISSUE TITLE
As the restaurant owner I want my staff to login, to view, modify and cancel customer reservations

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#20]

**Comment by chathugaj** [comment]
**Acceptance criteria**
- [x] Staff member can successfully login using username and password
- [x] Staff member can view a list of upcoming reservations
- [ ] The staff member can filter and search for reservations based on customer name
- [x] The staff member can view the details of a specific reservation
- [x] The staff member can modify certain details of a reservation and save the changes
- [x] The staff member can cancel a reservation

**Tasks**
- [x] The staff member should be able to enter their username and password to access the reservation management system
- [x] The staff member should be able to view a list of upcoming reservations, including details Customer name, table number, reservation date-time, number of guests
- [ ] The system should allow filtering and searching for reservations based customer name
- [x] The staff member should be able to view the details of a specific reservation by clicking on it
- [x] The staff member should be able to modify certain details of a reservation, including; date-time, number of guests, table number
- [x] The system should display any conflicts or limitations when modifying a reservation
- [x] The staff member should be able to save the changes made to the reservation
- [x] The staff member should be able to cancel an existing reservation
- [x] Cancellation should ask confirmation before the actual cancellation happens
