### ISSUE TITLE
As a user I want the application functionality for reservation, cancellation and view working without errors

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#22]
**Acceptance Criteria**

- [x] All necessary CRUD operations in the systems are implemented
- [x] CRUD operations can be performed without errors.

**Tasks**

- [x] Review and fix issues in CRUD operations.
