### ISSUE TITLE
As a user I want to perform actions in the system without getting any errors and/or not being prevented performing any actions as expected

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#24]
**Acceptance Criteria**

- [x] All functionality of the system is thoroughly tested.
- [x] Any issues found fixed

**Tasks**
- [x] Test the system
- [x] Fix any issues
