### ISSUE TITLE
As a developer I want the sensitive information not available in the committed code

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#25]
**Acceptance Criteria**

- [x] Sensitive information is removed from the repository
- [x] Proper configuration is done in the deployment environment

**Tasks**

- [x] Clean up the codebase.
- [x] Implement proper configuration in the deployment environment.
