### ISSUE TITLE
As a developer I need to add Javascript so that page have more dynamic functionality

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#5]

**Comment by chathugaj** [comment]
**Acceptance Criteria**
- [x] Identify functionalities to implement using javascript.
- [x] The JavaScript code is well-structured, and follows best practices.
- [x] The implemented functionality works as expected across different browsers and devices.

**Tasks**
- [x] Use Javascript in the application.
- [x] Use Javascript to implement selected features.
