### ISSUE TITLE
As a devleoper I need to setup the project with necesssary dependencies, so that I can develop the core features

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#6]

**Comment by chathugaj** [comment]
**Acceptance Criterial**
- [x] Identify all dependencies
- [x] Use a dependency management tool
- [x] Dependencies are successfully installed in the project directory.
- [x] The development environment is configured correctly.

**Tasks**
- [x] Identify and install suitable dependencies.
- [x] Configure the dependencies correctly
- [x] Setup dependency management
