### ISSUE TITLE
As a developer I need to implement a navbar so that I can enable navigation in my website

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#7]

**Comment by chathugaj** [comment]
**Acceptance Criteria**

- [x] The navbar includes clear navigation links to the website's main sections or pages.
- [x] The currently active page is visually indicated within the navbar.
- [x] The navbar design is responsive and adapts to different screen sizes.

**Tasks**

- [x] Implement a responsive navbar.
