### ISSUE TITLE
As a user I need to see a 404 error page, if the page I'm trying to access is not available

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/The-Dine-Restaurant#9]

**Comment by chathugaj** [comment]
**Acceptance Criteria**

- [x]  The system detects internal server errors and triggers an error page for 404 status code.
- [x]  A dedicated and visually distinct error page is displayed for 404 errors.
- [x]  The error page displays a user-friendly message explaining the error.
- [x]  The page provides guidance on how users can proceed.
- [x]  The website's branding is maintained on the error page.

**Tasks**

- [x]  Handle errors correctly in the system.
- [x]  Implement dedicated page for the http 404 errors.
- [x]  Provide clear messages and guidance to users.
